import initAccordion from './modules/accordion.js';
import initAnimaNumeros from './modules/anima-numeros.js';
import initAnimacaoScroll from './modules/animacao-scroll.js';
import initDropdownMenu from './modules/dropdown-menu.js';
import initFuncionamento from './modules/funcionamento.js';
import initMenuMobile from './modules/menu-mobile.js';
import initModal from './modules/modal.js';
import initScrollSuave from './modules/scroll-suave.js';
import initTabNav from './modules/tabnav.js';
import initToolTip from './modules/tooltip.js';

initAccordion();
initAnimaNumeros();
initAnimacaoScroll();
initDropdownMenu();
initFuncionamento();
initMenuMobile();
initModal();
initScrollSuave();
initTabNav();
initToolTip();